import pyautogui 
import keyboard 
#map : @6004660
def combo1():
    pyautogui.moveTo(1202,205)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(1325,230,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1225,291,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1225,291,duration=1)
def combo2():
    pyautogui.moveTo(1361,240)
    keyboard.send("3")
    for _ in range(6):
        keyboard.send("x")
    pyautogui.dragTo(1348,373,duration=1)
    keyboard.send("1")
    keyboard.send("z")
    pyautogui.dragTo(1377,200,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1336,443,duration=1)
    keyboard.send("3")
    keyboard.send("z")
    pyautogui.dragTo(1363,443,duration=1)
def combo3():
    pyautogui.moveTo(1337,274)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(1329,388,duration=1)
    keyboard.send("3")
    keyboard.send("z")
    pyautogui.dragTo(1329,388,duration=1)
    
keyboard.add_hotkey("p",combo1) 
keyboard.add_hotkey("o",combo2) 
keyboard.add_hotkey("l",combo3) 
keyboard.wait("ESC") 