import pyautogui
import keyboard
#MAP: @310529
def combo1():
    pyautogui.moveTo(913 , 297)
    keyboard.send("1")
    pyautogui.dragTo(898 , 317,duration=1)
    keyboard.send("2")
    keyboard.send("x")
    pyautogui.dragTo(967 , 299,duration=1)
    keyboard.send("2")
    keyboard.send("z")
    pyautogui.dragTo(759 , 245,duration=1)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(980 , 311,duration=1)
    keyboard.send("2")
    pyautogui.dragTo(980 , 311,duration=1)
def combo2():
    pyautogui.moveTo(729 , 304)
    keyboard.send("2")
    pyautogui.dragTo(900 , 293,duration=1.27)
    keyboard.send("2")
    keyboard.send("x")
    pyautogui.dragTo(759 , 245,duration=1)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(980 , 311,duration=1)
    keyboard.send("2")
    pyautogui.dragTo(980 , 311,duration=1)
def combo3():
    pyautogui.moveTo(969 , 193)
    keyboard.send("3")
    for i in range(6):
        keyboard.send("x")
    pyautogui.dragTo(987 , 382,duration=1)
    keyboard.send("1")
    keyboard.send("x")
    pyautogui.dragTo(992 , 373,duration=1)
    keyboard.send("3")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(992 , 373,duration=1)
def combo4():
     pyautogui.moveTo(917 , 198)
     keyboard.send("2")
     keyboard.send("z")
     keyboard.send("z")
     keyboard.send("z")
     keyboard.send("z")
     keyboard.send("z")
     pyautogui.dragTo(883 , 404,duration=1)
     keyboard.send("2")
     keyboard.send("x")
     pyautogui.dragTo(883 , 404,duration=1)
keyboard.add_hotkey("p",combo1)
keyboard.add_hotkey("o",combo2)
keyboard.add_hotkey("l",combo3)
keyboard.add_hotkey("k",combo4)
keyboard.wait("ESC")