import keyboard
import pyautogui
#map : @1539148
def combo1():
    pyautogui.moveTo(1273 , 200)
    keyboard.send("3")
    keyboard.send('x')
    keyboard.send('x')
    keyboard.send('x')
    keyboard.send('x')
    keyboard.send('x')
    pyautogui.dragTo(1273 , 200,duration=1)
    keyboard.send("3")
    keyboard.send('x')
    keyboard.send('x')
    keyboard.send('x')
    keyboard.send('x')
    keyboard.send('x')
    pyautogui.dragTo(1397 , 286,duration=1)
    keyboard.send("3")
    pyautogui.dragTo(1199 , 216, duration=1)
    keyboard.send("1")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1374 , 185, duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1374 , 185, duration=1)
def combo2():
    pyautogui.moveTo(1415 , 283)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1428 , 219,duration=1.17)
    keyboard.send("3")
    keyboard.send("x")
    pyautogui.dragTo(1415 , 283,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1428 , 219,duration=1.17)
    keyboard.send("3")
    keyboard.send("x")
    pyautogui.dragTo(1428 , 219,duration=1)
keyboard.add_hotkey("p", combo1)
keyboard.add_hotkey("o", combo2)
keyboard.wait("ESC")
