#map : @7943171
import pyautogui
import keyboard
def combo1():
    pyautogui.moveTo(1424 , 205)
    keyboard.send("1")
    keyboard.send("x")
    pyautogui.dragTo(1405 , 186, duration=1.1)
    keyboard.send("1")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1257 , 315, duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1257 , 315, duration=1)
def combo2():
    pyautogui.moveTo(1246 , 386)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(1369 , 455,duration=1)
    keyboard.send("3")
    pyautogui.dragTo(1346 , 375,duration=1)
    keyboard.send("1")
    keyboard.send("x")
    pyautogui.dragTo(1400 , 367,duration=1)
    keyboard.send("3")
    pyautogui.dragTo(1400 , 367,duration=1)
def combo3():
    pyautogui.moveTo(1259 , 193)
    keyboard.send("1")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1219 , 285,duration=1)
    keyboard.send("3")
    pyautogui.dragTo(1219 , 285,duration=1)

keyboard.add_hotkey("p",combo1)
keyboard.add_hotkey("o",combo2)
keyboard.add_hotkey("l",combo3)
keyboard.wait("ESC")
