import pyautogui
import keyboard
#MAP: @305748
def combo1():
        pyautogui.moveTo(935,310)
        keyboard.send("1")
        pyautogui.dragTo(945,314,duration=1)
        keyboard.send("3")
        keyboard.send("x")
        keyboard.send("x")
        pyautogui.dragTo(1034 , 195,duration=1)
        keyboard.send("3")
        keyboard.send("z")
        keyboard.send("z")
        pyautogui.dragTo(962 , 190,duration=1)
def combo2():
        pyautogui.moveTo(962 , 190)
        keyboard.send("1")
        keyboard.send("X")
        pyautogui.dragTo(897 , 381, duration=1)
        keyboard.send("3")
        keyboard.send("X")
        keyboard.send("X")
        pyautogui.dragTo(897 , 381, duration=1)
def combo3():
        pyautogui.moveTo(966 , 203)
        keyboard.send("1")
        keyboard.send("X")
        pyautogui.dragTo(930 , 365, duration=1)
        keyboard.send("3")
        keyboard.send("X")
        keyboard.send("X")
        pyautogui.dragTo(930 , 365, duration=1)
def combo4():
        pyautogui.moveTo(970 , 191)
        keyboard.send("3")
        keyboard.send("z")
        keyboard.send("z")
        keyboard.send("z")
        keyboard.send("z")
        keyboard.send("z")
        pyautogui.dragTo(882 , 389, duration=1)
        keyboard.send("3")
        pyautogui.dragTo(882 , 389, duration=1)
def combo5():
        pyautogui.moveTo(974 , 189)
        keyboard.send("3")
        keyboard.send("x")
        keyboard.send("x")
        keyboard.send("x")
        keyboard.send("x")
        pyautogui.dragTo(974 , 189, duration=1)

keyboard.add_hotkey("p",combo1)
keyboard.add_hotkey("o",combo2)
keyboard.add_hotkey("l",combo3)
keyboard.add_hotkey("k",combo4)
keyboard.add_hotkey("j",combo5)
keyboard.wait("ESC")
