#map : @6240668
import pyautogui
import keyboard
def combo1():
    pyautogui.moveTo(891 , 311)
    keyboard.send("2")
    pyautogui.dragTo(930 , 379, duration=1)
    keyboard.send("3")
    keyboard.send("Z")
    keyboard.send("Z")
    pyautogui.dragTo(930 , 379, duration=1)
def combo2():
    pyautogui.moveTo(1002 , 130)
    keyboard.send("3")
    keyboard.send("X")
    keyboard.send("X")
    keyboard.send("X")
    keyboard.send("X")
    keyboard.send("X")
    pyautogui.dragTo(954 , 373, duration=1)
    keyboard.send("3")
    keyboard.send("Z")
    keyboard.send("Z")
    pyautogui.dragTo(954 , 373, duration=1)
def combo3():
    pyautogui.moveTo(921 , 122)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(957 , 370, duration=1)
    keyboard.send("2")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(957 , 370, duration=1)
def combo4():
    pyautogui.moveTo(1029 , 309)
    keyboard.send("3")
    pyautogui.dragTo(980 , 370, duration=1)
    keyboard.send("2")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(980 , 370, duration=1)

keyboard.add_hotkey("P", combo1)
keyboard.add_hotkey("O", combo2)
keyboard.add_hotkey("L", combo3)
keyboard.add_hotkey("K", combo4)
keyboard.wait("ESC")
