
import pyautogui
import keyboard
#map : @7522912
def combo1():
    pyautogui.moveTo(1006 , 291)
    keyboard.send("1")
    pyautogui.dragTo(1032 , 263,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(954 , 321,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(954 , 321,duration=1)
def combo2():
    pyautogui.moveTo(1009 , 282)
    keyboard.send("1")
    pyautogui.dragTo(1201 , 298,duration=1)
    keyboard.send("3")
    pyautogui.dragTo(1197 , 219,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(971 , 280,duration=1)
    keyboard.send("3")
    pyautogui.dragTo(971 , 280,duration=1)
def combo3():
    pyautogui.moveTo(976 , 291)
    keyboard.send("1")
    pyautogui.dragTo(987 , 218,duration=1)
    keyboard.send("3")
    for i in range(6):
        keyboard.send("x")
    pyautogui.dragTo(1145 , 398,duration=1)
    keyboard.send("3")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1006 , 359,duration=1)
    keyboard.send("3")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(1006 , 359,duration=1)
def combo4(): #833 , 371
    pyautogui.moveTo(616, 403)
    keyboard.send("2")
    keyboard.send("x")
    pyautogui.dragTo(823 , 442,duration=1.24)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(759 , 476,duration=1)
    keyboard.send("2")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(759 , 476,duration=1)
keyboard.add_hotkey("p",combo1)
keyboard.add_hotkey("o",combo2)
keyboard.add_hotkey("l",combo3)
keyboard.add_hotkey("k",combo4)
keyboard.wait("ESC")