import pyautogui
import keyboard
#map : @848697
def combo1():
    pyautogui.click(1412 ,863)
    pyautogui.moveTo(960 ,462)
    for i in range(6):
        keyboard.send("x")
    pyautogui.dragTo(960 ,462, duration=1)
def combo2():
    pyautogui.moveTo(1000 , 391)
    keyboard.send("3")
    for i in range(6):
        keyboard.send("x")
    pyautogui.dragTo(994 , 429,duration=1)
    keyboard.send("1")
    pyautogui.dragTo(994 , 429,duration=1)
def combo3():
    pyautogui.moveTo(1026 , 318)
    keyboard.send("1")
    pyautogui.dragTo(1005 , 332,duration=1)
    keyboard.send("1")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(1092 , 329,duration=1)
    keyboard.send("2")
    keyboard.send("x")
    keyboard.send("x")
    pyautogui.dragTo(1092 , 329,duration=1)
def combo4():
    pyautogui.moveTo(886 , 204)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(901 , 199,duration=1)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(1058 , 407,duration=1)
    keyboard.send("2")
    keyboard.send("z")
    pyautogui.dragTo(948 , 193,duration=1)
    keyboard.send("2")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    keyboard.send("z")
    pyautogui.dragTo(948 , 193,duration=1)
keyboard.add_hotkey("p", combo1)
keyboard.add_hotkey("o", combo2)
keyboard.add_hotkey("l", combo3)
keyboard.add_hotkey("k", combo4)
keyboard.wait("ESC")